obj1:
  name: 'VISIBLE_FLOOR'
  file: '/home/konishi/catkin_ws/kojio_tutorial/src/rtm-ros-robotics/rtmros_choreonoid/jvrc_models/models/visible_floor.wrl'
  translation: [0, 0, -0.1]
  rotation: [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
